### ISSUE TITLE
Kernel Panic with same Booter Quirks setting from OpenCore Bootloader

### ISSUE THREAD

**Issue by andreszerocross** [ReddestDream/OcQuirks#10]
![Screen Shot 2019-12-23 at 19 46 43](https://user-images.githubusercontent.com/9614101/71359111-d755ea00-25bd-11ea-8600-87c87b12de08.png)
I have set same configuration OcQuirks.plist with my working Config.plist of OpenCore Bootloader.

I can boot normally with OpenCore Bootloader but fail and ended with kernel panic with OcQuirks.efi + FwRuntimeService.efi.

Here is the picture of Kernel Panic
![IMG_3968](https://user-images.githubusercontent.com/9614101/71359177-16843b00-25be-11ea-9320-6b6bc0b1377c.png)

Just for Info my computer specifications 
Proc : Intel Core i7 6700
Motherboard : Gigabyte Z170X Gaming 7
GPU : MSI Armor RX 580 4GB
Ram : 16GB

But thanks for your work, i use OcQuirks.efi + FwRuntimeServices.efi in my Dell E5450 with Clover r5101 and working normally (with same booter Quirks config from OpenCore bootloader).

I don't know why it's kernel panic in my PC,, i try to set ShrinkMemoryMap=Yes or ProvideCustomSlide = Yes or ProtectCsmRegion = Yes or ForceExitBootServices = Yes and other but still get Kernel Panic. In my OC Configuration i just need to set "AvoidRuntimeDefrag + EnableWriteUnprotector + SetupVirtualMap = YES".

Thanks you

**Comment by ReddestDream** [comment]
Do you still get the kernel panic if you don’t use a plist at all? OcQuirks will use my default settings if there no plist. It’s possible there’s still something wrong with the plist override. 

But generally if OcQuirks were broken, you just couldn’t boot. You wouldn’t even get a panic. So that suggests that maybe something else is wrong with your system . . .

**Comment by andreszerocross** [comment]
Yes, it's still kernel panic. I forgot to say, i use it without OcQuirks.plist in first, after i get Kernel Panic, i tried to use same config with my config.plist of OC but then kernel panic is still there

**Comment by andreszerocross** [comment]
> Do you still get the kernel panic if you don’t use a plist at all? OcQuirks will use my default settings if there no plist. It’s possible there’s still something wrong with the plist override.
> 
> But generally if OcQuirks were broken, you just couldn’t boot. You wouldn’t even get a panic. So that suggests that maybe something else is wrong with your system . . .

There is nothing wrong with my System. I have working Clover and and OpenCore bootloader here. There is no problem after all.

I just change AptioMemoryFix.efi and replace with OcQuirks.efi and FwRuntimeService.efi,, OcBootloader and Clover bootloader use same SSDT and kexts and boot normally

**Comment by ReddestDream** [comment]
For some systems with given kexts and hardware, AptioMemoryFix may still work better.

I’m not sure what’s wrong from that kernel panic alone. Sorry. :/

I’m still not even sure there’s an OcQuirks issue here unfortunately, and this is an issue reporting list, not a troubleshooting forum. Try providing more info about your setup and kexts and ask on /r/hackintosh or their Discord (where I am active) or any other hackintosh troubleshooting forum.

**Comment by ReddestDream** [comment]
Oh. One last thing: you might try recompiling OcQuirks with your settings instead of using the plist. Plist code is still very new and it might not be overriding the defaults. That’s about all I can think in how OcQuirks could be responsible for your issue.

**Comment by andreszerocross** [comment]
> For some systems with given kexts and hardware, AptioMemoryFix may still work better.
> 
> I’m not sure what’s wrong from that kernel panic alone. Sorry. :/
> 
> I’m still not even sure there’s an OcQuirks issue here unfortunately, and this is an issue reporting list, not a troubleshooting forum. Try providing more info about your setup and kexts and ask on /r/hackintosh or their Discord (where I am active) or any other hackintosh troubleshooting forum.

Let's me clear one thing,, my computer specifications above is working fine with CLover and OC Bootloader 0.5.4. So no i don't need to provide anything in OpenCore Bootloader thread because there is no problem with OpenCore itself.

Which forum should i provide??? This is clearly a bug / issut and not my computer problem. I repeat,, I have used Oc Bootloader with latest commit and i compiled it by myself and my computer is running normally with that :)

**Comment by ReddestDream** [comment]
Did you try compiling OcQuirks with your settings, changing the default to match your OC plist?

If you want, I’ll make it for you for you to test. Again, could be an issue with the plist not being processed and the default settings not working on your hardware, tho I tried very hard to make sure they should work on all 100/200/370 boards.

**Comment by ReddestDream** [comment]
I think I might know what's wrong now. lol.
I've made a new version for you to test. Please let me know if this fixes the panic for you.
[OcQuirks_TEST_andreszerocross.zip](https://github.com/ReddestDream/OcQuirks/files/3995388/OcQuirks_TEST_andreszerocross.zip)

Use this w/o any plist included with it pls. Thanks! :)

**Comment by andreszerocross** [comment]
> Did you try compiling OcQuirks with your settings?

Yes, i have tried it. I have edit **OcQuirks.c** and set "AvoidRuntimeDefrag, EnableWriteUnprotector, ProvideConsoleGopEnable and SetupVirtualMap with TRUE" then i recompiled it with macbuild.too. Reboot and i still get kernel panic with it.

This is my Drivers files
![image](https://user-images.githubusercontent.com/9614101/71365602-1857f980-25d2-11ea-955b-47531c68d066.png)

**Comment by ReddestDream** [comment]
Try this new version above and see if it works. Thanks!

**Comment by ReddestDream** [comment]
Also please try removing FSInject and EnglishDXE as they might conflict with OcQuirks.

**Comment by andreszerocross** [comment]
> Also please try removing FSInject and EnglishDXE as they might conflict with OcQuirks.

Tried your file above with no change, it's still kernel panic.
As far as i know,, FSInject.efi is needed to inject kext. EnglishDXE is about shell feature. But i will give a try

**Comment by ReddestDream** [comment]
Welp. Sorry that didn’t work. :/

FSInjext is not required to inject kexts. Please remove it too and test. Thanks!

**Comment by andreszerocross** [comment]
> Welp. Sorry that didn’t work. :/
> 
> FSInjext is not required to inject kexts. Please remove it too and test. Thanks!

I tested your files, remove EnglishDxe.efi and FSInject.efi too. With same result kernel panic about invalid frame pointer bla bla,, check first screenshot

**Comment by ReddestDream** [comment]
Have you tried recompiling AppleSupportPkg to get a fresh FwRunTimeServices? Only because I notice yours is about a month old. Probably won’t fix it, but it’s something else to try.

**Comment by andreszerocross** [comment]
> Have you tried recompiling AppleSupportPkg to get a fresh FwRunTimeServices? Only because I notice yours is about a month old. Probably won’t fix it, but it’s something else to try.

I am compiling it now,, i will give report ASAP

**Comment by andreszerocross** [comment]
> Have you tried recompiling AppleSupportPkg to get a fresh FwRunTimeServices? Only because I notice yours is about a month old. Probably won’t fix it, but it’s something else to try.

You're right,, with new FwRunTimeServices (i compiled it again recently) then i can boot normally. Sorry, this is my mistake.

You're the best
![image](https://user-images.githubusercontent.com/9614101/71369000-0b400800-25dc-11ea-9fab-66783f46b5c4.png)

**Comment by ReddestDream** [comment]
Great! Glad we got it fixed! :)

Edit: I realize now that with the date on your old FwRuntimeService (Nov 27), you were missing the latest refactor/rebase of AppleSupportPkg on Nov 30. That’s why you had trouble. Should’ve noticed this earlier. Sorry.

**Comment by jiggers84** [comment]
I’m having the same issue. 
![2D4FF769-4412-4B30-BC98-8C54E237DBFB](https://user-images.githubusercontent.com/34467623/74173412-4c719300-4bef-11ea-8fc5-bbd4098bf3b8.jpeg)

**Comment by sarabveer** [comment]
If anyone here is experiencing the same Kernel Panic, please set `RebuildAppleMemoryMap` to `false` and `EnableWriteUnprotector` to `true`.

**Comment by hhs98** [comment]
Ahh Sarabveer I can't Thank you enough man <3. Thank you so much
@Sarabveer

**Comment by ftpman** [comment]
@hhs98 me too !! Thank you @Sarabveer !! 🙌🏼

**Comment by liuerpeng1** [comment]
@Sarabveer Many many thanks!!!

**Comment by heavyflusen** [comment]
> If anyone here is experiencing the same Kernel Panic, please set `RebuildAppleMemoryMap` to `false` and `EnableWriteUnprotector` to `true`.

I was searching for this for so many hours! THANK YOU! @Sarabveer

**Comment by xino1010** [comment]
@Sarabveer thank you so much!!!

**Comment by Diddicrafter** [comment]
@Sarabveer WOW thank you, you are my hero <3

**Comment by frankkuipersgit** [comment]
@Sarabveer Thank you! You saved my day

**Comment by Harshit7780** [comment]
> Great! Glad we got it fixed! :)
> 
> Edit: I realize now that with the date on your old FwRuntimeService (Nov 27), you were missing the latest refactor/rebase of AppleSupportPkg on Nov 30. That’s why you had trouble. Should’ve noticed this earlier. Sorry.



> > Have you tried recompiling AppleSupportPkg to get a fresh FwRunTimeServices? Only because I notice yours is about a month old. Probably won’t fix it, but it’s something else to try.
> 
> You're right,, with new FwRunTimeServices (i compiled it again recently) then i can boot normally. Sorry, this is my mistake.
> 
> You're the best
> ![image](https://user-images.githubusercontent.com/9614101/71369000-0b400800-25dc-11ea-9fab-66783f46b5c4.png)

Even I'm getting this error with opencore 0.6.4. So do I need to add FwRuntimeService.efi into driver folder??

**Comment by Harshit7780** [comment]
> ![Screen Shot 2019-12-23 at 19 46 43](https://user-images.githubusercontent.com/9614101/71359111-d755ea00-25bd-11ea-8600-87c87b12de08.png)
> I have set same configuration OcQuirks.plist with my working Config.plist of OpenCore Bootloader.
> 
> I can boot normally with OpenCore Bootloader but fail and ended with kernel panic with OcQuirks.efi + FwRuntimeService.efi.
> 
> Here is the picture of Kernel Panic
> ![IMG_3968](https://user-images.githubusercontent.com/9614101/71359177-16843b00-25be-11ea-9320-6b6bc0b1377c.png)
> 
> Just for Info my computer specifications
> Proc : Intel Core i7 6700
> Motherboard : Gigabyte Z170X Gaming 7
> GPU : MSI Armor RX 580 4GB
> Ram : 16GB
> 
> But thanks for your work, i use OcQuirks.efi + FwRuntimeServices.efi in my Dell E5450 with Clover r5101 and working normally (with same booter Quirks config from OpenCore bootloader).
> 
> I don't know why it's kernel panic in my PC,, i try to set ShrinkMemoryMap=Yes or ProvideCustomSlide = Yes or ProtectCsmRegion = Yes or ForceExitBootServices = Yes and other but still get Kernel Panic. In my OC Configuration i just need to set "AvoidRuntimeDefrag + EnableWriteUnprotector + SetupVirtualMap = YES".
> 
> Thanks you

Even I'm getting this error with opencore 0.6.4. So do I need to add OcQuirks.efi + FwRuntimeService.efi into driver folder??

**Comment by ReddestDream** [comment]
This is a closed thread. Please do not post here. Thank you.

Also, yes, you need both (FwRuntimeService.efi is now OpenRuntime.efi). 

But the whole point of this project is for non-OpenCore bootloaders.

If you are already using OpenCore, you don't want/need this project at all.

Also, as you can tell, I haven't had time to work on this since Sept. I don't use it myself anymore and the important bits have already been incorporated into Clover. Thanks!

**Comment by vjonas** [comment]
> If anyone here is experiencing the same Kernel Panic, please set `RebuildAppleMemoryMap` to `false` and `EnableWriteUnprotector` to `true`.

Thank you! I forgot to enable the `EnableWriteUnprotector`. Works fine now. Even though it was in the docs, I must have overlooked.
