### ISSUE TITLE
Can't boot Allocating error

### ISSUE THREAD

**Issue by telepati** [ReddestDream/OcQuirks#11]
I tried almost every AptioMemoryFix efi's but cant boot; I tried this and getting this error;

ERROR allocating 0x119e1 pages at 0x0000000006257000 alloc type 2
Couldn't allocate runtime area
Boot failed: will sleep for 10 seconds before exiting...

If I used AptioMemoryFix.efi this time I am getting this error;

AMF: No slide values are usable! Falling back to 0 with 0x17771000 bytes!
ERROR allocating 0x119e1 pages at 0x0000000006257000 alloc type 2
Couldn't allocate runtime area
Boot failed: will sleep for 10 seconds before exiting...

**Comment by Matgen84** [comment]
I've randomly the same issue with OcQuirks Release 9 on Z390 Aorus Master (10.15.3 Beta 1)

**Comment by telepati** [comment]
> I've randomly the same issue with OcQuirks Release 9 on Z390 Aorus Master (10.15.3 Beta 1)

OcQuirks 9 never works me either on my Z390 Gaming. But If I add OcQuirks-4.efi+EmuVariableUefi.efi I can boot. I don't get it what is the differences between OcQuirks 9 and OcQuirks-4?

**Comment by Matgen84** [comment]
> > I've randomly the same issue with OcQuirks Release 9 on Z390 Aorus Master (10.15.3 Beta 1)
> 
> OcQuirks 9 never works me either on my Z390 Gaming. But If I add OcQuirks-4.efi+EmuVariableUefi.efi I can boot. I don't get it what is the differences between OcQuirks 9 and OcQuirks-4?

Where do you find OcQuirks-4.efi?

**Comment by telepati** [comment]
> > > I've randomly the same issue with OcQuirks Release 9 on Z390 Aorus Master (10.15.3 Beta 1)
> > 
> > 
> > OcQuirks 9 never works me either on my Z390 Gaming. But If I add OcQuirks-4.efi+EmuVariableUefi.efi I can boot. I don't get it what is the differences between OcQuirks 9 and OcQuirks-4?
> 
> Where do you find OcQuirks-4.efi?

Try those;
[Archive.zip](https://github.com/ReddestDream/OcQuirks/files/4003160/Archive.zip)

**Comment by ReddestDream** [comment]
I don't know where this "OcQuirks-4.efi" came from but it's not an official release.

Perhaps it was compiled with different settings? You might need different settings from the default for Z390. I don't have any Z390 boards myself. You need EmuVariableUefi.efi on Z390 because native NVRAM doesn't work.

AFAICT, this isn't really issue reporting. It's Z390 troubleshooting and this issue page isn't really the appropriate place for this. Thanks!
