### ISSUE TITLE
nasm error?

### ISSUE THREAD

**Issue by telepati** [ReddestDream/OcQuirks#13]
Hi, I am trying to create a new OCQuirck. Getting this error; It doesnt allow me to install nasm.

![Screen Shot 2019-12-27 at 06 19 26](https://user-images.githubusercontent.com/3812286/71499329-12337880-2871-11ea-981f-3fd6e84c1313.png)

**Comment by ReddestDream** [comment]
Create the directory /usr/local/bin if it doesn’t already exist. Systems like homebrew will make it for you.

**Comment by telepati** [comment]
Thanks to you I compiled.
