### ISSUE TITLE
Merge with FwRuntimeServices

### ISSUE THREAD

**Issue by ppkdsvbs** [ReddestDream/OcQuirks#15]
Hi,

it is possible to merge OCQuirks and FwRuntimeServices into one efi driver?

**Comment by ReddestDream** [comment]
Maybe, but I have no interest in doing so as it would likely greatly increase the cost of maintenance. I like to keep OcQuirks simple. But if you are interested in doing it, I’d consider a pull request to OcQuirks that would do this. Thanks!
