### ISSUE TITLE
OcSupportPkg compatibility

### ISSUE THREAD

**Issue by vit9696** [ReddestDream/OcQuirks#16]
Hello,

We made some internal changes in regards to OpenCore ←→ FwRuntimeServices compatibility. Since FwRuntimeServices is very close to OpenCore and OcSupportPkg, OcAppleBootCompatLib in particular, we moved FwRuntimeServices to be part of OcSupportPkg. From now on we will release FwRuntimeServices with OpenCore.

For your project this means that it is best to do the same, and distribute your own version of FwRuntimeServices with OcQuirks. Such approach should ensure compatibility between the drivers.

Also, while this is unrelated, we plan to perform further in AppleSupportPkg projects to improve integration with OpenCore. That means that some drivers will become OcSupportPkg libraries, and for those who want to use them in third-party projects, OcQuirks-like approach will be best. It will be great if you continue such work if you feel interested.

Best wishes,
Vit

**Comment by ReddestDream** [comment]
Thanks so much! Really appreciate your support! :)

This really makes things a lot easier and will help users keep their builds of FwRuntimeServices and OcQuirks in sync.

**Comment by vit9696** [comment]
Thanks. The issue can be closed now I suppose.

**Comment by ReddestDream** [comment]
Sounds good!
