### ISSUE TITLE
i5-1035G1 using ERROR

### ISSUE THREAD

**Issue by GatesYang** [ReddestDream/OcQuirks#19]
Thank you for your hard work~! My laptop is Lenovo S740 with i5-1035G1. I have used all the "OsxAptioFix~" and "AptioMemoryFix~" as wll as OcQuirks. However, I never succeed in entering install interface and I got "ERROR allocating 0x83368 pages at 0x000000000fd53000 alloc type 2".Only when using OcQuirks the "0x000000000fd53000" would change every reboot, though the "OsxAptioFix" or "AptioMemoryFix" show the same value every reboot. What should I do? T_T

**Comment by ReddestDream** [comment]
This is not a support forum. Try different OcQuirks settings and other standard memory/booting troubleshooting procedures. Thanks!
