### ISSUE TITLE
rev22 crashes 10.15.4  z270XP-SLI

### ISSUE THREAD

**Issue by exquirentibus** [ReddestDream/OcQuirks#24]
I'm running Clover 5107 (and have also tried 5109).

Using latest Weg, Lilu, AppleALC. FakeSMC.kext, XHCI-unsupported.kext, USBInjectAll.kext (as verified by Hackintool) and custom .aml for USB.

UEFI drivers (besides OcQuirks):
ApfsDriverLoader.efi, FSInject.efi, VBoxHfs.efi all dated 2/16/20

After Clover SSD selected, it starts for about 2 seconds and reboots 100%.

If I go back to rev 20, it doesn't reboot and I have no issues.

Great tools, had zero problem before this!!  If there's some debug log I can get you, let me know?

**Comment by ReddestDream** [comment]
The defaults have changed slightly with this latest release. What OcQuirks settings are you using? Z270XP-SLI might require EnableWriteUnprotector to be enabled in order to boot . . .

**Comment by exquirentibus** [comment]
I have never changed the default setting in the OcQuirks.plist, so whatever is the default in rev22 is what I'm using.   I'll enable EnableWriteUnprotector later today if you believe that will resolve this?  Is there log output I can look at for issues, or is the correct method to use -v and record a video?

**Comment by ReddestDream** [comment]
Before you spend too much more time, yeah. Just try EnableWriteUnprotector. Seems to be necessary for 100/200 Gigabyte boards. If that doesn’t work, we can investigate more, but I think that will probably fix it. Thanks!

**Comment by exquirentibus** [comment]
I was able to boot after enabling EnableWriteUnprotector.   Thanks!!

**Comment by ReddestDream** [comment]
Great!
