### ISSUE TITLE
No boot after upgrade to build 22

### ISSUE THREAD

**Issue by BbIKTOP** [ReddestDream/OcQuirks#25]
Have updated ocquirks to 22 and now my os does not boot. And even better - it does not boot after I used usb flash drive with previously working efi and after I restored my efi to the previously working version (I always make a backup before any changes). Tried to reset nvram, checked and found it completely clear and empty. Still able to boot to the recovery or installer with the same efi. Clover 5108

![IMG_3971](https://user-images.githubusercontent.com/24525137/78665998-5ce87600-78df-11ea-99c2-ac43636f1c6b.png)
![IMG_3972](https://user-images.githubusercontent.com/24525137/78666032-683ba180-78df-11ea-8862-05225abc7932.png)
![IMG_3970](https://user-images.githubusercontent.com/24525137/78666058-738ecd00-78df-11ea-9151-6cfc801afb27.png)

**Comment by ReddestDream** [comment]
Not sure what happened here. But if you have a 100/200 series Intel board, you can try EnableWriteUnprotector. Some boards do need that and it is disabled in build 22 for safety (and many boards are fine with RebuildAppleMemoryMap).

**Comment by BbIKTOP** [comment]
I also don't understand. Looks like it broke something in the os itself. Sorry, my fault, forgot to mention that I have ga z390i wifiI with 9900k. I returned back my previous efi - copied complete whole efi partition, with previous ocquirks and its config, and still have the same problem.

**Comment by ReddestDream** [comment]
Yeah. I'm not sure how it could break something in the OS itself. Other users have reported success with this latest version. :/

**Comment by BbIKTOP** [comment]
I have no idea as well, but here's the result I've got

**Comment by BbIKTOP** [comment]
A bit more info. Just managed to restore from timemachine backup on another drive. So now I have one efi partition that I use to boot 2 copies of the same installation - first one is the current one that is not working since upgrade, and second is a backup copy made right before ocquirks update. And now I am able to boot second and still not able to boot first. Looks like ocquirks broke something in the macos itself; will try to restore /System/Library/PrelinkedKernels and let you know

**Comment by BbIKTOP** [comment]
Well,  -f UseKernelCache=No didn't help
Managed to restore /System/Library/PrelinkedKernels/* from backup and now everything is working

**Comment by laelsirus** [comment]
I have the same issue with my Latitude 5290 2-in-1
It works fine until Revision 20.1, but issues have occurred since Revision 21.

On the other hand, it works fine on the desktop of the Asus Strix B360-I board.

**Comment by BbIKTOP** [comment]
Ok, I could give it another try. What config would you recommend to try for 21, if my fully working config for 20 is as follows:



    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
            <key>AvoidRuntimeDefrag</key>
            <true/>
            <key>SetupVirtualMap</key>
            <true/>
            <key>ProvideCustomSlide</key>
            <true/>
            <key>DevirtualiseMmio</key>
            <false/>
            <key>DisableSingleUser</key>
            <false/>
            <key>DiscardHibernateMap</key>
            <false/>
            <key>EnableSafeModeSlide</key>
            <true/>
            <key>ProtectCsmRegion</key>
            <false/>
            <key>ShrinkMemoryMap</key>
            <false/>
            <key>ForceExitBootServices</key>
            <true/>
            <key>DisableVariableWrite</key>
            <false/>
            <key>EnableWriteUnprotector</key>
            <true/>
            <key>ProvideConsoleGopEnable</key>
            <true/>
            <key>SignalAppleOS</key>
            <false/>
    </dict>
    </plist>

**Comment by ReddestDream** [comment]
@BbIKTOP @laelsirus You should both try using the new default config + EnableWriteUnprotector on non-working Skylake or newer systems. If it still does not work, let me know. That seems to be the most common fix people (including myself) need with this new version. I didn't enable EnableWriteUnprotector by default as it risks memory corruption and should not be enabled unless it is required to boot and/or fix NVRAM. RebuildAppleMap is now the preferred method and it should be enabled along with EnableWriteUnprotector if possible if EnableWriteUnprotector is needed. 

So, all you need to do is try the new default config and enable EnableWriteUnprotector. Leave everything else alone. See if that boots. If not, we can change more.

@laelsirus Your B360-I is likely new enough that the MAT table is in place and it does not require EnableWriteUnprotector. Therefore, it works with the default config. :)

Boards with firmware originally built in mid-2018 or later generally should work w/o issue with the new default config. It's only boards with older firmware that should need EnableWriteUnprotector. Make sure you update your firmware to the latest. Thanks!

**Comment by BbIKTOP** [comment]
Sorry for delay, macos urgently wanted to install some supplementary update.
So. Just installed build 22 with the default config and clover 5108 and can confirm that now everything is working. Z390I wifi pro, i9900k. So, it can be closed now, thank you. I suppose I don't need to change anything in the default config then?

**Comment by BbIKTOP** [comment]
Wow, I suppose I found the reason. Will check it further, but highly likely it all was caused by the new clover 5109, not ocquirks. Sorry if it is so, will ask Sergey to help.

**Comment by ReddestDream** [comment]
Great! Thanks! 👍
