### ISSUE TITLE
MacOS 10.15.4 not booting with v. 22

### ISSUE THREAD

**Issue by lucaszischka** [ReddestDream/OcQuirks#26]
Since I updated to v. 22 macOS isn't booting anymore. I'm using Clover v. 5111. After I've downgraded everything works just fine again.

**Comment by ReddestDream** [comment]
Hardware? You probably just need to turn on EnableWriteUnprotector. See other recent closed issues. Thanks!

**Comment by lucaszischka** [comment]
Ok i will try booting with "EnableWriteUnprotector" turned on.

**Comment by lucaszischka** [comment]
Didn't worked with "EnableWriteUnprotector" turned on. 

Hardware:
Laptop - Acer Nitro 5 AN515-52
Intel i7 Core 8.th Gen CoffeLake (i7-8750H) + Intel UHD 630
16gb RAM
(Disabeld: GeForce GTX 1060)
1TB HDD - no SSD

Dual Booting with windows

Clover: 5111
Drivers: ApfsDriverLoder, OcQuriks, FSInject, OpenRuntime, VBoxHfs, VirtualSmc
SSDT-GPIO and SSDT-XOSI are patched

If you need more infos, please ask

Any Ideas? Thanks

**Comment by ReddestDream** [comment]
**More Troubleshooting Steps:**

1. Make sure your OpenRuntime version matches the OcQuirks version (use the OpenRuntime.efi from the release zip.)

2. Remove potentially unneeded driver (FSInject and VirtualSmc).

3. The new settings with this version are SyncRuntimePermissions, RebuildAppleMemoryMap, and ProtectMemoryRegions (replaces ProtectCSMRegions, not relevant on your hardware). Try playing with SyncRuntimePermissions and/or RebuildAppleMemoryMap and/or EnableWriteUnprotector (disabled by default on this version, but it was on by default on previous versions).

4. Make sure you have the latest BIOS from your OEM.

5. Confirm that you can boot correctly with an older version of OcQuirks to rule out a Clover issue (recent releases have been buggy).

6. Remove slide=X from your boot-args if present. This conflicts with the OcQuirks fixes.

These are just some ideas. This latest release works fine for many people and is not broken; however, it did introduce several new options from upstream OpenCorePkg and I changed the defaults for added compatibility and safety with the latest hardware, so you may need to play with settings as indicated above to find what works for your hardware. Thanks!

**Comment by lucaszischka** [comment]
The last hour I tried various combinations of SyncRuntimePermissions, RebuildAppleMemoryMap, and EnableWriteUnprotector; for me worked:

SRP -> off, RAMP ->  off, EWU -> on,
SRP -> on, RAMP ->  off, EWU -> on,
SRP -> off, RAMP ->  off, EWU -> off

=>  The RAMP (**RebuildAppleMemoryMap**) option was the problem. It is the only option that needed to be changed (to **OFF**), but I could change SRP and EWU without a problem.

I also tried step 2 and MacOS also booted fine without FSInject. Why? All my kext are at Clover/Kexts/Other?

**Comment by ReddestDream** [comment]
> SRP -> on, RAMP -> off, EWU -> on

Glad you got it working! :)

This is probably the safest one and should still have working NVRAM. You might also try turning off SetupVirtualMap and see if turning that off lets you keep RAMP on. RAMP is a new fix designed to fix some recently discovered issues and to provide an alternative to EWU, which is known to be buggy. Not all boards can use it tho.

> I also tried step 2 and MacOS also booted fine without FSInject. Why? All my kext are at Clover/Kexts/Other?

Yeah. You shouldn't need FSInject on modern versions of macOS, especially if all your kexts are in Clover\Kexts\Other.

**Comment by lucaszischka** [comment]
> This is probably the safest one and should still have working NVRAM. You might also try turning off SetupVirtualMap and see if turning that off lets you keep RAMP on. RAMP is a new fix designed to fix some recently discovered issues and to provide an alternative to EWU, which is known to be buggy. Not all boards can use it tho.

I've tried turning off SetupVirtualMap and turning RAMP on, but it won't boot :( 

Going to stick with:
> > SRP -> on, RAMP -> off, EWU -> on

**Comment by ReddestDream** [comment]
Sounds good! 👍
