### ISSUE TITLE
apfs volumes booting stuck on ++++

### ISSUE THREAD

**Issue by rdmitry0911** [ReddestDream/OcQuirks#27]
I have LG 17 Gram laptop 17z990. I can boot it with almost everything but can't boot apfs volumes. Of cause these apfs volumes are bootable. I can boot easily from those apfs volumes on my desktop system. 
I tried different versions of clover and ocquirks, tried playing with ocquirks setting but nothing works. 
It always stuck like this:

...
Start FinalizeBootStruct
Start RandomSeed
End RandomSeed
++++++++++++++++++++++++++++++++++++++++++++

The working config that boots everything including windows, linux and macos 10.15.3 is based on clover 5112, ocquirks 22 and this qcquirks.plist:
AvoidRuntimeDefrag	true
DevirtualiseMmio	true
DisableSingleUser	false
DisableVariableWrite	false
DiscardHibernateMap	false
EnableSafeModeSlide	true
EnableWriteUnprotector	true
ForceExitBootServices	true
MmioWhitelist	array
ProtectMemoryRegions	false
ProtectSecureBoot	false
ProtectUefiServices	true
ProvideConsoleGopEnable	true
ProvideCustomSlide	true
RebuildAppleMemoryMap	false
SetupVirtualMap	true
SignalAppleOS	false
SyncRuntimePermissions	true

**Comment by ReddestDream** [comment]
OcQuirks doesn’t handle APFS. For that you need to make sure you have ApfsDriverLoader. Make sure you try both Clover’s (older) version and the (now discontinued) Acidanthera version in AppleSupportPkg.

You may also need to try changing some settings in the config plist. Can you provide specs for the LG 17 Gram laptop 17z990?

I see that RebuildAppleMemoryMap is off. Have you tried it on? I see EnableWriteUnprotector is on. Have you tried it off? Just examples. I need specs to be more specific. Thanks!

**Comment by rdmitry0911** [comment]
Of cause, ApfsDriverLoader is loaded. I'll check with Acidanthera version. 
I didn't know any config setting specific to apfs booting.  In any case I shared my efi folder [here](https://drive.google.com/file/d/12F0lvUKEgLVyOlFL1EYkBw3KwanMTMLo/view?usp=sharing) 
laptop spes are as follows:
- i7-8565u
- uhd620 whyskey lake
- 16GB ram
- nvme 1TB intel
RebuildAppleMemoryMap off is critical. Without it I stuck in the +++++++++++++
EnableWriteUnprotector should be on, otherwise I have panic

**Comment by rdmitry0911** [comment]
I tried ApfsDriverLoader  from AppleSupport-v2.0.3-DEBUG - no effect

**Comment by ReddestDream** [comment]
Okay. Your best option is to continue to play with the config plist settings. Try to figure out exactly which options are essential and which combinations of them boot and which don't. Try other typical memory issue troubleshooting like disabling SGX, Thunderbolt, CSM, etc.

As to why you specifically can't load APFS volumes, I truly have no idea. That's not an OcQuirks issue. You are free to post here, but be aware this is for issue reporting, not support. There are other forums you can go to support. I'm going to close this as an issue.

Also, I looked at your EFI and OcQuirks isn't even there. Instead you've got OsxAptioFix3Drv.efi. I can't help you with that. Thanks!

**Comment by rdmitry0911** [comment]
Ok, thank you. I'll try other options

**Comment by ReddestDream** [comment]
Cool. Let me know if you have further questions.
