### ISSUE TITLE
Another fix compilation need

### ISSUE THREAD

**Issue by Matgen84** [ReddestDream/OcQuirks#28]
Hi

I try to build OcQuirks without success this morning. I don't understand why. Please help me.

`Building ... /Users/mathieu/OcQuirks/UDK/MdeModulePkg/Library/BaseSerialPortLib16550/BaseSerialPortLib16550.inf [X64]
make: *** No rule to make target `/Users/mathieu/OcQuirks/UDK/EfiPkg/Include/Protocol/DataHub.h', needed by `/Users/mathieu/OcQuirks/UDK/Build/OcQuirks/DEBUG_XCODE5/X64/OpenCorePkg/Library/OcDataHubLib/OcDataHubLib/OUTPUT/DataHub.obj'.  Stop.

build.py...
 : error 7000: Failed to execute command
	make tbuild [/Users/mathieu/OcQuirks/UDK/Build/OcQuirks/DEBUG_XCODE5/X64/OpenCorePkg/Library/OcDataHubLib/OcDataHubLib]

build.py...
 : error F002: Failed to build module
	/Users/mathieu/OcQuirks/UDK/OpenCorePkg/Library/OcDataHubLib/OcDataHubLib.inf [X64, XCODE5, DEBUG]

- Failed -
Build end time: 07:52:25, May.26 2020
Build total time: 00:00:02

./macbuild.tool: line 67:  5532 Terminated: 15          pingme $! build "$@"
logout`

**Comment by ReddestDream** [comment]
Builds fine for me just now and it built fine for me yesterday morning when I last checked.

Tell me more about your build system/environment. You might try re-cloning everything again. Thanks!

**Comment by Matgen84** [comment]
I use Mojave / Xcode 11.3.1

I build from scratch: all works fine now.
Thanks!

**Comment by ReddestDream** [comment]
Thanks!
