### ISSUE TITLE
Can't build 

### ISSUE THREAD

**Issue by Matgen84** [ReddestDream/OcQuirks#29]
Hi 

I can't build OcQuirks again (Mojave - Xcode 11.3.1). The error message below:

`Processing meta-data .Architecture(s)  = X64
Build target     = DEBUG
Toolchain        = XCODE5

Active Platform          = /Users/mathieu/OcQuirks/UDK/OcQuirks/OcQuirks.dsc

build.py...
/Users/mathieu/OcQuirks/UDK/OcQuirks/OcQuirks.dsc(...): error 4000: Instance of library class [TimerLib] is not found
	in [/Users/mathieu/OcQuirks/UDK/OpenCorePkg/Library/OcBootManagementLib/OcBootManagementLib.inf] [X64]
	consumed by module [/Users/mathieu/OcQuirks/UDK/OcQuirks/Platform/OcQuirks/OcQuirks.inf]
 

- Failed -`

**Comment by ReddestDream** [comment]
Probably due to this recent change. I'll look into it when I have time to test compiling again. Should have time in the next few days.

https://github.com/acidanthera/OpenCorePkg/commit/da902fe3c69b7f9c4d14147f0465b8e8ce06a484

**Comment by Matgen84** [comment]
Thanks for your future test and thanks for OcQuirks
