### ISSUE TITLE
BlackScreen on Bios with aptio fixes

### ISSUE THREAD

**Issue by e-senturk** [ReddestDream/OcQuirks#5]
Hi, I have weird issue since final release of catalina. My Nvram works with osxaptio 1, 3, osxaptio2-wtf and aptioinput aswell but after catalina if I boot even once with these drivers, I cant access bios. When I try it hang out in black screen. If I use osxaptio2 all the time I can access bios but mlb and rom values becaming 0. Also if I get blackscreen once only way to revert that reflashing nvram with amibios tool. I have also tried OpenCore it has same issue as well. I have never experianced that kind of issue before on mojave. 
 Then I find that thread modified QcQuirks but only way to keep bios alive disabling mac's access to nvram "DisableVariableWrite" in that way nvram becoming meaningless("Nvram can't keep brightness value that way").

Device: Asus FX553VD i-7700hq.

**Comment by ReddestDream** [comment]
If the issue exists on OC, it will likely occur with this as well as it uses OC's code. Not sure how to resolve your issue, but if you can figure it out with OC, it might also work here.
