### ISSUE TITLE
OcQuirks.efi Revision 7 not working with latest FwRuntimeservices.efi

### ISSUE THREAD

**Issue by 1alessandro1** [ReddestDream/OcQuirks#7]
I'm trying to boot as you described in the ReadMe file in your repository, and I had no issues since the previous latest release of AppleSupportPkg: https://github.com/acidanthera/AppleSupportPkg/releases/tag/2.1.2

Now with the latest release https://github.com/acidanthera/AppleSupportPkg/releases/tag/2.1.4 I cannot use OcQuirks Rev7 with the latest FwRuntimeservices from Acidanthera, the system restarts even before loading the kernel probably because of NVRAM management in the latest release of FwRuntimeServices. Please let us know when a new version of OcQuirks.efi will support the latest FwRuntimeservices 2.1.4

Thank you

**Comment by ReddestDream** [comment]
Yeah. I need to fix it up for the new releases. Planning to do it today or tomorrow. Hopefully this week if anything. Thanks!

**Comment by ReddestDream** [comment]
@1alessandro1 If you'd like, please help me test by verifying that this newly recompiled build works for you. Thanks!

https://www.dropbox.com/s/30760om5l3wo4gj/OcQuirks-R8-RELEASE.zip?dl=0

**Comment by ejkarne** [comment]
> @1alessandro1 If you'd like, please help me test by verifying that this newly recompiled build works for you. Thanks!
> 
> https://www.dropbox.com/s/30760om5l3wo4gj/OcQuirks-R8-RELEASE.zip?dl=0

Fixed it for me 🤠👍

**Comment by 1alessandro1** [comment]
Thanks again for quick response. I tested your Dropbox version (Rev 8) and it seems to be working perfectly: no issues so far, back to normal. 
Can Rev 8 be considered as a stable release or still beta, pre-release? 
Can you please list the changes that were applied in the latest commit?

**Comment by ReddestDream** [comment]
No changes. I just incremented the number and recompiled it. ;p

I'll post it as a release later today. Thanks!

**Comment by ReddestDream** [comment]
Updated.
